### ISSUE TITLE
Raspberry Pi 3 dies while running Malos Eye example

### ISSUE THREAD

**Issue by luisnomad** [matrix-io/matrix-creator-quickstart#22] opened 2017-01-23 19:14 UTC
I am able to run the example query_demographics.js, but after a few seconds the raspberry crashes badly, and I have to hard reset it (unplug the cable). Also since I installed Malos, I have noticed that the raspberry struggles to do anything. It's a brand new Raspberry Pi 3, so it should work right?

**Comment by brianofrokk3r** [comment] 2017-01-24 16:18
Duplicate of https://github.com/matrix-io/malos-eye/issues/5

**Closed as completed by brianofrokk3r** 2017-01-24 16:18 UTC
